language: node_js
node_js:
  - "node"
install:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  repo: dev
  local-dir: docs
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
